// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+SW32vjOBDH/5Uwd49OnLYvxY+XhhK4yy1JAwulFMWeOCq2pEqjbkPw/76MHDs/26bQ",
	"hYV9M8rMd74z85GdNaS6NFqhIgfJGly6xFKEx4G3FlW64mdUvoTkHmbTG4hgOJtABP99H8NDBLQyCAk4",
	"slLlUEVt3kQQjrIJOqOVQ1YxVhu0JDHop5u4RysIH2XGZ6/dXHc3it7LrDebjbhie96VpdGWgpqgJSSQ",
	"S1r6eS/VZZxrnRcYcyJUVRWBxWcvLWZs/ajc1rueP2FKh97fdv71XiNgVxy50LYUBAksCi0IIlC+KMS8",
	"QEjIemw9K1/O0cIm806W+9mZIOwSn76psN2YI0E+dPa3xQUk8Fe8pSLeIBHvzmZaZxzOWGbQqn003mlb",
	"tIFrOhsMhtMpRPBtOL4ZjW8Ztcnk/8lJzIbWanuCKp3tT0IqurqEVkAqwrweXInOiTxEH6gfosOa2/jj",
	"zjhBqoUOUpJ41E2vbCuCF7ROagUJXPT6vT5X1waVMBISuApHUYAk9BA3rMYvF3EDhtEuoJShS600VMtN",
	"UWUdb3jdnSarwykdbgAdE8TjERw/yiCBMf7YXUOoa0WJhNZBcn9YoBU1QlrgNiGBZ492xWQJxg42P21H",
	"VnNWg3NqvA8cXN+u0PBl/6LenSJUoUthTCHT4Dp+cuxkvaN3LqY7r5+wo/3WBnvz4nvIEQvhC/oyNzWl",
	"J4p7ha8GU8Ksg01MFR2vPl7PhcMqXpOwOVLFBXM8QcItUqcQjg4wWGjbrG6fg1ukf4Wjz7Dwj3BbyhoW",
	"wqutRYHNvovCOavjC3hY+y60/0H1ekZfUf+Y0P4vIfRsPn9TOGX2PpH7MM5XnfCJOCLxMxQeXduTKITz",
	"tzFoPw/hAxyd8Yb64/fPfxTQvjRL8baABJZEJonjQqeiWGpHyXX/ug/VQ/UzAAD//9dV5KVZCgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
