// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"time"

	"github.com/google/uuid"
)

// Defines values for Currency.
const (
	EUR Currency = "EUR"
	MXN Currency = "MXN"
	USD Currency = "USD"
)

// Defines values for CurrencyRateStatus.
const (
	ERROR   CurrencyRateStatus = "ERROR"
	PENDING CurrencyRateStatus = "PENDING"
	SUCCESS CurrencyRateStatus = "SUCCESS"
)

// Currency defines model for Currency.
type Currency string

// CurrencyRateIdResponse defines model for CurrencyRateIdResponse.
type CurrencyRateIdResponse struct {
	CurrencyRateId uuid.UUID `json:"currency_rate_id"`
}

// CurrencyRateResponse defines model for CurrencyRateResponse.
type CurrencyRateResponse struct {
	Id       uuid.UUID          `json:"id"`
	Rate     *float32           `json:"rate"`
	RateTime *time.Time         `json:"rateTime"`
	Status   CurrencyRateStatus `json:"status"`
}

// CurrencyRateStatus defines model for CurrencyRateStatus.
type CurrencyRateStatus string

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewCurrencyRateParams defines parameters for NewCurrencyRate.
type NewCurrencyRateParams struct {
	// Pair currency pair
	Pair string `form:"pair" json:"pair"`
}
